### ISSUE TITLE
Set things up 

### ISSUE THREAD

**Issue by BrishaP** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-super-awesome-team-name#3]
```[tasklist]
### Tasks
- [x] Install packages. Run npm install
- [x] Create database in Render
- [x] Add environment variable in Render
- [x] Add environment variables to .env example and rename the file
- [x] Start the app and see if it works (console.log)
- [x] Create a basic README with 'getting' started section
```
