### ISSUE TITLE
Change file names

### ISSUE THREAD

**Issue by BrishaP** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-super-awesome-team-name#4]
```[tasklist]
### Tasks
- [x] Change helper file name
- [x] Change helper file function names
- [x] Change the request handler URLS
- [x] Test the new request handlers work/can be called
```
